apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ca-certificate
spec:
  commonName: Server CA
  isCA: true
  issuerRef:
    kind: Issuer
    name: selfsigned-ca
  secretName: server-ca-certificate
